version: '3'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend_container
    ports:
      - "8000:8000"
    networks:
      - our_network
    depends_on:
      - postgres   # This ensures the Django container starts after the PostgreSQL container


  postgres:
    image: postgres
    container_name: postgres_db_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: mmensing
      POSTGRES_PASSWORD: '0000'
    networks:
      - our_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

##    healthcheck:
##      test: [ "CMD-SHELL", "pg_isready -U mmensing -d mmensing -h localhost -p 5432" ]


networks:
  our_network:
volumes:
  postgres_data: